global:
# How frequently to scrape targets by default.
scrape_interval: 15s

# How frequently to evaluate rules.
evaluation_interval: 15s

# A list of scrape configurations.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'spring-actuator'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.21.143.4:8080']
